### ISSUE TITLE
Error on scraping: The page does not exist, please check the URL

### ISSUE THREAD

**Issue by megariffer** [Lehoczky/apro-scrape#1]
Üdv! Bármilyen linket adok be a kezdésnél, mindig ezt írja:
_The page does not exist, please check the URL_

Próbáltam windows tűzfalon engedélyezni, nem segített.
Windows 11-en próbálkozom. A visszadobott linket próbáltam böngészőben, tökéletes.
A default linkkel se működik.

Nem pont ide tartozik, csak infó: a windows defender megfogta a telepítőt.

Köszi előre is a segítséget. Pont ilyen appot keresetem, de sajna nem tudom működésre bírni...

**Comment by Lehoczky** [comment]
Hali,
Kijavítottam a hibát, a [legújabb release](https://github.com/Lehoczky/apro-scrape/releases/tag/v1.2.1)-el már működik nálam.
